# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39bdf423dcc6a2fd8944ae67a5665a928904c644321a2c72e1f29447c5f57442530a9d452a2b8b4a4c429ac4c2903af48cff395ad18e565503fee97bd9b3a3fb

test:
  secret_key_base: 2ea369065f29de95cee99b9b049b31f409685b9fc2ca1f2dfd685282ee61474375256b8934b3d7c12d07733ab4b8d19496f96d52178b73591e9e3aa353c604c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
